### ISSUE TITLE
Error in Polyphony columns ??

### ISSUE THREAD

**Issue by gluon** [iftah-og/Synthesizers-1896-2024#2] opened 2024-10-29 07:18 UTC
Hi Iftah,
running the notebook, after having created and activated a venv, and installed these: 
pip3 install pandas
pip3 install sklearn
pip3 install sklearn-learn
pip3 install scikit-learn
pip3 install matplotlib
pip3 install seaborn
pip3 install wordcloud
pip3 install squarify

and I got these errors :

[error_iftah.txt](https://github.com/user-attachments/files/17553025/error_iftah.txt)

This is probably from my side, but I'd love to solve this to... explore :-)

**Comment by iftah-og** [comment] 2024-10-29 20:52
Hi, thanks for reporting, the error was caused by a none numeric value in the polyphony column which is now fixed in the latest revision of the dataset.

**Closed as completed** 2024-11-01 13:54 UTC
